version: 2
jobs:
  build:
    working_directory: /go/src/github.com/yansal/circleci-elasticsearch
    docker:
      - image: circleci/golang:1.10.3
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    steps:
      - checkout
      - run:
          name: Waiting for elasticsearch to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 9200 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for elasticsearch && exit 1
      - run: go test
